
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_shortlink_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.shortlink: DEBUG
