
server {
    listen 80;
    listen 443 ssl;
    server_name s.xxx.com;

    ssl_certificate /usr/local/openresty/ssl/s.xxx.com.crt;
    ssl_certificate_key /usr/local/openresty/ssl/s.xxx.com.key;

    log_format link_log_json '{"time":"$time_iso8601","code":"$uri","ip":"$remote_addr"}';
    access_log /usr/local/openresty/logs/short_access.log link_log_json;

    location ~ ^/([0-9a-zA-Z]+)$ {
        content_by_lua_file /usr/local/openresty/lua/link_redirect.lua;
    }

    location /fallback/link {
        proxy_pass http://127.0.0.1:8080/api/link/fallback;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
